### ISSUE TITLE
Team Meeting - September 27 2023 @ 4:00pm

### ISSUE THREAD

**Issue by davimang** [davimang/REACH#5]
### Topics
- Further discussion of SRS

**Comment by deep123845** [comment]
Using simplified Volere Template
Requirements brainstorm:
- register account
- login to account
- login as guest
- retrieve trial data from repository
- filter trials using given attributes
- location/range preference
- medical condition
- height
- weight
- sex
- advanced search options(ie. detailed medical history)
- notifications for new studies
- generate email template for studies
- faqs/learning about trials

Non-Functional Requirements:

- translations

david 3, 5
annika 6
alan 2, 8
aamina 1, 
deep 4
n/a 7,9

Deep Section 1 for intro

Section 4

David 9, 10
Annika 6, 7, 8
Aaamina 1-5
