### ISSUE TITLE
Look into email notification systems

### ISSUE THREAD

**Issue by davimang** [davimang/REACH#74]

**Comment by davimang** [comment]
- How can sending email notifications be implemented?
- Should we/will we have to implement this from the ground up, or is there a third party solution already available to use and integrate with a django app?

**Comment by Computerized** [comment]
Twilio SendGrid - up to 100 emails/day for free. Python supported.

Has a Python library [sendgrid](https://github.com/sendgrid/sendgrid-python/)

[https://sendgrid.com/en-us/pricing](https://sendgrid.com/en-us/pricing)
