### ISSUE TITLE
UI for landing page

### ISSUE THREAD

**Issue by davimang** [davimang/REACH#97]
issue description below

**Comment by aami-hus** [comment]
implement a basic ui design for the landing/home page of REACH. components on the page don't have to be functional as their functionality will be implemented as part of future issues.

[figma design](https://www.figma.com/file/58wCxZa5xulKIIYw8eX8Pr/REACH-Trial-Functionality?type=design&node-id=10-3&mode=design&t=7ORxJMyqW4EYrApW-0)
